//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBooks2goV5.ebookapps {
    
    
    public partial class xebookapps {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// accebookapps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.Accordion accebookapps;
        
        /// <summary>
        /// accpaneebookapps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane accpaneebookapps;
        
        /// <summary>
        /// rbebookappssimpleebookapps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton rbebookappssimpleebookapps;
        
        /// <summary>
        /// lnkbtnebookappssimpleebookapps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkbtnebookappssimpleebookapps;
        
        /// <summary>
        /// lblebookappssimpleebookappsdefaultpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappsdefaultpages;
        
        /// <summary>
        /// AccordionPane2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane AccordionPane2;
        
        /// <summary>
        /// rbebookappscomplexebookapps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton rbebookappscomplexebookapps;
        
        /// <summary>
        /// lnkbtnebookappscomplexebookapps control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkbtnebookappscomplexebookapps;
        
        /// <summary>
        /// lblebookappscomplexebookappsdefaultpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsdefaultpages;
        
        /// <summary>
        /// lblebookappscomplexebookappsdefaultanimationpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsdefaultanimationpages;
        
        /// <summary>
        /// lblebookappscomplexebookappsanimationcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsanimationcost;
        
        /// <summary>
        /// AccordionPane3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.AccordionPane AccordionPane3;
        
        /// <summary>
        /// rbebookappsfortextbooks control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton rbebookappsfortextbooks;
        
        /// <summary>
        /// lnkbtneBookAppstextbook control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton lnkbtneBookAppstextbook;
        
        /// <summary>
        /// lblebookappsfortextbooksdefaultpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksdefaultpages;
        
        /// <summary>
        /// pnlSimple control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlSimple;
        
        /// <summary>
        /// lblebookappssimplebookappsoffer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimplebookappsoffer1;
        
        /// <summary>
        /// lblebookappssimplebookappsoffer1discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimplebookappsoffer1discount;
        
        /// <summary>
        /// lblebookappssimplebookappsoffer2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimplebookappsoffer2;
        
        /// <summary>
        /// lblebookappssimplebookappsoffer2discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimplebookappsoffer2discount;
        
        /// <summary>
        /// lblebookappssimplebookappsoffer3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimplebookappsoffer3;
        
        /// <summary>
        /// lblebookappssimplebookappsoffer3discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimplebookappsoffer3discount;
        
        /// <summary>
        /// pnlebookappssimpleebookappsproducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlebookappssimpleebookappsproducts;
        
        /// <summary>
        /// chkebookappssimpleebookappsipad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappssimpleebookappsipad;
        
        /// <summary>
        /// lblebookappssimpleebookappsipadproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappsipadproductcost;
        
        /// <summary>
        /// chkebookappssimpleebookappsiphone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappssimpleebookappsiphone;
        
        /// <summary>
        /// lblebookappssimpleebookappsiphoneproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappsiphoneproductcost;
        
        /// <summary>
        /// chkebookappssimpleebookappsandroidtablets control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappssimpleebookappsandroidtablets;
        
        /// <summary>
        /// lblebookappssimpleebookappsandroidtabletsproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappsandroidtabletsproductcost;
        
        /// <summary>
        /// chkebookappssimpleebookappsandroidphones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappssimpleebookappsandroidphones;
        
        /// <summary>
        /// lblebookappssimpleebookappsandroidphonesproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappsandroidphonesproductcost;
        
        /// <summary>
        /// txtebookappssimpleebookappspackagecost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappssimpleebookappspackagecost;
        
        /// <summary>
        /// lblebookappssimpleebookappscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappscustpages;
        
        /// <summary>
        /// lblebookappssimpleebookappscustpagescost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappscustpagescost;
        
        /// <summary>
        /// txtebookappssimpleebookappscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappssimpleebookappscustpages;
        
        /// <summary>
        /// fteebookappssimpleebookappscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender fteebookappssimpleebookappscustpages;
        
        /// <summary>
        /// lblebookappssimpleebookappsadditionalpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappsadditionalpages;
        
        /// <summary>
        /// lblebookappssimpleebookappsadditonalpagesunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappsadditonalpagesunitcost;
        
        /// <summary>
        /// lblebookappssimpleebookappsadditionaltotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappssimpleebookappsadditionaltotalcost;
        
        /// <summary>
        /// imgbtnsimpleproceed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton imgbtnsimpleproceed;
        
        /// <summary>
        /// pnlComplex control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlComplex;
        
        /// <summary>
        /// lblebookappscomplexebookappsoffer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsoffer1;
        
        /// <summary>
        /// lblebookappscomplexebookappsoffer1discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsoffer1discount;
        
        /// <summary>
        /// lblebookappscomplexebookappsoffer2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsoffer2;
        
        /// <summary>
        /// lblebookappscomplexebookappsoffer2discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsoffer2discount;
        
        /// <summary>
        /// lblebookappscomplexebookappsoffer3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsoffer3;
        
        /// <summary>
        /// lblebookappscomplexebookappsoffer3discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsoffer3discount;
        
        /// <summary>
        /// pnlebookappscomplexebookappsproducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlebookappscomplexebookappsproducts;
        
        /// <summary>
        /// chkebookappscomplexebookappsipad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappscomplexebookappsipad;
        
        /// <summary>
        /// lblebookappscomplexebookappsipadproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsipadproductcost;
        
        /// <summary>
        /// chkebookappscomplexebookappsiphone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappscomplexebookappsiphone;
        
        /// <summary>
        /// lblebookappscomplexebookappsiphoneproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsiphoneproductcost;
        
        /// <summary>
        /// chkebookappscomplexebookappsandroidtablets control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappscomplexebookappsandroidtablets;
        
        /// <summary>
        /// lblebookappscomplexebookappsandroidtabletsproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsandroidtabletsproductcost;
        
        /// <summary>
        /// chkebookappscomplexebookappsandroidphones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappscomplexebookappsandroidphones;
        
        /// <summary>
        /// lblebookappscomplexebookappsandroidphonesproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsandroidphonesproductcost;
        
        /// <summary>
        /// txtebookappscomplexebookappspackagecost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappscomplexebookappspackagecost;
        
        /// <summary>
        /// lblebookappscomplexebookappscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappscustpages;
        
        /// <summary>
        /// lblebookappscomplexebookappscustpagescost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappscustpagescost;
        
        /// <summary>
        /// txtebookappscomplexebookappscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappscomplexebookappscustpages;
        
        /// <summary>
        /// fteebookappscomplexebookappscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender fteebookappscomplexebookappscustpages;
        
        /// <summary>
        /// lblebookappscomplexebookappsadditionalpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsadditionalpages;
        
        /// <summary>
        /// lblebookappscomplexebookappsaddtionalpagesunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsaddtionalpagesunitcost;
        
        /// <summary>
        /// lblebookappscomplexebookappsadditionalpagestotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsadditionalpagestotalcost;
        
        /// <summary>
        /// lblebookappscomplexebookappscustanimationpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappscustanimationpages;
        
        /// <summary>
        /// lblebookappscomplexebookappscustanimationpagescost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappscustanimationpagescost;
        
        /// <summary>
        /// txtebookappscomplexebookappscustanimationpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappscomplexebookappscustanimationpages;
        
        /// <summary>
        /// fteebookappscomplexebookappscustanimationpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender fteebookappscomplexebookappscustanimationpages;
        
        /// <summary>
        /// lblebookappscomplexebookappsadditionalanimationpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsadditionalanimationpages;
        
        /// <summary>
        /// lblebookappscomplexebookappsadditionalanimationpagesunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsadditionalanimationpagesunitcost;
        
        /// <summary>
        /// lblebookappscomplexebookappsadditionalanimationpagestotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappscomplexebookappsadditionalanimationpagestotalcost;
        
        /// <summary>
        /// imgbtncomplexproceed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton imgbtncomplexproceed;
        
        /// <summary>
        /// pnltxtbok control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnltxtbok;
        
        /// <summary>
        /// lblebookappsfortextbooksoffer1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksoffer1;
        
        /// <summary>
        /// lblebookappsfortextbooksoffer1discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksoffer1discount;
        
        /// <summary>
        /// lblebookappsfortextbooksoffer2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksoffer2;
        
        /// <summary>
        /// lblebookappsfortextbooksoffer2discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksoffer2discount;
        
        /// <summary>
        /// lblebookappsfortextbooksoffer3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksoffer3;
        
        /// <summary>
        /// lblebookappsfortextbooksoffer3discount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksoffer3discount;
        
        /// <summary>
        /// pnlebookappsfortextbooksproducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlebookappsfortextbooksproducts;
        
        /// <summary>
        /// chkebookappsfortextbooksipad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappsfortextbooksipad;
        
        /// <summary>
        /// lblebookappsfortextbooksipadproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksipadproductcost;
        
        /// <summary>
        /// chkebookappsfortextbooksiphone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappsfortextbooksiphone;
        
        /// <summary>
        /// lblebookappsfortextbooksiphoneproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksiphoneproductcost;
        
        /// <summary>
        /// chkebookappsfortextbooksandroidtablets control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappsfortextbooksandroidtablets;
        
        /// <summary>
        /// lblebookappsfortextbooksandroidtabletsproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksandroidtabletsproductcost;
        
        /// <summary>
        /// chkebookappsfortextbooksandroidphones control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkebookappsfortextbooksandroidphones;
        
        /// <summary>
        /// lblebookappsfortextbooksandroidphonesproductcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksandroidphonesproductcost;
        
        /// <summary>
        /// txtebookappsfortextbookspackagecost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappsfortextbookspackagecost;
        
        /// <summary>
        /// lblebookappsfortextbookscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbookscustpages;
        
        /// <summary>
        /// lblebookappsfortextbookscustpagescost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbookscustpagescost;
        
        /// <summary>
        /// txtebookappsfortextbookscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappsfortextbookscustpages;
        
        /// <summary>
        /// fteebookappsfortextbookscustpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender fteebookappsfortextbookscustpages;
        
        /// <summary>
        /// lblebookappsfortextbooksadditionalpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksadditionalpages;
        
        /// <summary>
        /// lblebookappsfortextbooksadditionalpagesunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksadditionalpagesunitcost;
        
        /// <summary>
        /// lblebookappsfortextbooksadditionalpagestotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksadditionalpagestotalcost;
        
        /// <summary>
        /// lblebookappsfortextbookscustinteractiveselfassessmentpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbookscustinteractiveselfassessmentpages;
        
        /// <summary>
        /// lblebookappsfortextbookscustinteractiveselfassessmentpagescost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbookscustinteractiveselfassessmentpagescost;
        
        /// <summary>
        /// txtebookappsfortextbookscustinteractiveandselfassessmentpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappsfortextbookscustinteractiveandselfassessmentpages;
        
        /// <summary>
        /// fteebookappsfortextbooksinteractiveassessement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender fteebookappsfortextbooksinteractiveassessement;
        
        /// <summary>
        /// lblebookappsfortextbooksadditionalinteractiveselfassessmentpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksadditionalinteractiveselfassessmentpages;
        
        /// <summary>
        /// lblebookappsfortextbooksadditionalinteractiveselfassessmentunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksadditionalinteractiveselfassessmentunitcost;
        
        /// <summary>
        /// lblebookappsfortextbooksadditionalinteractiveselfassessmenttotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbooksadditionalinteractiveselfassessmenttotalcost;
        
        /// <summary>
        /// lblebookappsfortextbookscustavintergrationpages control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbookscustavintergrationpages;
        
        /// <summary>
        /// lblebookappsfortextbookscustavintergrationpagescost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappsfortextbookscustavintergrationpagescost;
        
        /// <summary>
        /// txtebookappsfortextbookscustavelements control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtebookappsfortextbookscustavelements;
        
        /// <summary>
        /// fteebookappsfortextbooksaudioandvideo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::AjaxControlToolkit.FilteredTextBoxExtender fteebookappsfortextbooksaudioandvideo;
        
        /// <summary>
        /// lblebookappstextbooksadditionalavelements control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappstextbooksadditionalavelements;
        
        /// <summary>
        /// lblebookappstextbooksadditionalavelementsunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappstextbooksadditionalavelementsunitcost;
        
        /// <summary>
        /// lblebookappstextbooksadditionalavelementstotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblebookappstextbooksadditionalavelementstotalcost;
        
        /// <summary>
        /// imgbtntextbook control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton imgbtntextbook;
    }
}
