//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBooks2goV5.pricing {
    
    
    public partial class enhancedebookcart {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// lblcartid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblcartid;
        
        /// <summary>
        /// lblEnhancedeBooktitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooktitle;
        
        /// <summary>
        /// lblEnhancedeBookproduct control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookproduct;
        
        /// <summary>
        /// lblEnhancedeBookauthor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookauthor;
        
        /// <summary>
        /// lblEnhancedeBookepubquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookepubquantity;
        
        /// <summary>
        /// lblEnhancedeBookepubunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookepubunitcost;
        
        /// <summary>
        /// lblEnhancedeBookepubtotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookepubtotalcost;
        
        /// <summary>
        /// lblEnhancedeBookmobiquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookmobiquantity;
        
        /// <summary>
        /// lblEnhancedeBookmobiunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookmobiunitcost;
        
        /// <summary>
        /// lblEnhancedeBookmobitotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookmobitotalcost;
        
        /// <summary>
        /// lblEnhancedeBooknookquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooknookquantity;
        
        /// <summary>
        /// lblEnhancedeBooknookunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooknookunitcost;
        
        /// <summary>
        /// lblEnhancedeBooknooktotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooknooktotalcost;
        
        /// <summary>
        /// lblEnhancedeBookcustpagesquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcustpagesquantity;
        
        /// <summary>
        /// lblEnhancedeBookcustpagesunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcustpagesunitcost;
        
        /// <summary>
        /// lblEnhancedeBookcustpagestotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcustpagestotalcost;
        
        /// <summary>
        /// lblEnhancedeBookcustlinksquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcustlinksquantity;
        
        /// <summary>
        /// lblEnhancedeBookcustlinksunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcustlinksunitcost;
        
        /// <summary>
        /// lblEnhancedeBookcustlinkstotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcustlinkstotalcost;
        
        /// <summary>
        /// lblEnhancedeBooknestedtocquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooknestedtocquantity;
        
        /// <summary>
        /// lblEnhancedeBookdropcapsquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookdropcapsquantity;
        
        /// <summary>
        /// lblEnhancedeBookcoloredfontsquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcoloredfontsquantity;
        
        /// <summary>
        /// lblEnhancedeBooklistsquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooklistsquantity;
        
        /// <summary>
        /// lblEnhancedeBooksectionsquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooksectionsquantity;
        
        /// <summary>
        /// lblEnhancedeBookcalloutsquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcalloutsquantity;
        
        /// <summary>
        /// lblEnhancedeBookdoublecolumntextquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookdoublecolumntextquantity;
        
        /// <summary>
        /// lblEnhancedeBookcenteredtextquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcenteredtextquantity;
        
        /// <summary>
        /// lblEnhancedeBooktextboxcolorsquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooktextboxcolorsquantity;
        
        /// <summary>
        /// lblEnhancedeBookavelementsquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookavelementsquantity;
        
        /// <summary>
        /// lblEnhancedeBookavelementsunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookavelementsunitcost;
        
        /// <summary>
        /// lblEnhancedeBookavelementstotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookavelementstotalcost;
        
        /// <summary>
        /// lblEnhancedeBooktexthighlightsquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooktexthighlightsquantity;
        
        /// <summary>
        /// lblEnhancedeBooktexthighlightsunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooktexthighlightsunitcost;
        
        /// <summary>
        /// lblEnhancedeBooktexthighlightstotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooktexthighlightstotalcost;
        
        /// <summary>
        /// lblEnhancedeBookcoverdesignquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcoverdesignquantity;
        
        /// <summary>
        /// lblEnhancedeBookcoverdesignunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcoverdesignunitcost;
        
        /// <summary>
        /// lblEnhancedeBookcoverdesigntotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookcoverdesigntotalcost;
        
        /// <summary>
        /// lblEnhancedeBookeisbnquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookeisbnquantity;
        
        /// <summary>
        /// lblEnhancedeBookeisbnunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookeisbnunitcost;
        
        /// <summary>
        /// lblEnhancedeBookeisbntotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookeisbntotalcost;
        
        /// <summary>
        /// lblEnhancedeBookdistributionquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookdistributionquantity;
        
        /// <summary>
        /// lblEnhancedeBookmarketingservicesquantity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookmarketingservicesquantity;
        
        /// <summary>
        /// lblEnhancedeBookmarketingservicesunitcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookmarketingservicesunitcost;
        
        /// <summary>
        /// lblEnhancedeBookmarketingservicestotalcost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookmarketingservicestotalcost;
        
        /// <summary>
        /// lblEnhancedeBookgrandtotal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookgrandtotal;
        
        /// <summary>
        /// lblEnhancedeBookdiscountonbasepkg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookdiscountonbasepkg;
        
        /// <summary>
        /// lblEnhancedeBooktotaldiscount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBooktotaldiscount;
        
        /// <summary>
        /// lblEnhancedeBookestimatedcartvalue control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEnhancedeBookestimatedcartvalue;
        
        /// <summary>
        /// Imgbtnback control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton Imgbtnback;
    }
}
